version: '3'

tasks:
  readme-build:
    dir: packages/bankuu-info-readme
    cmds:
      - venv/bin/python3 main.py

  readme-watch:
    cmds:
      - find packages/bankuu-info-readme/ | entr task readme-build