# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: packages/bankuu-info-readme
    - name: Run main.py
      run: |
        python main.py
      working-directory: packages/bankuu-info-readme
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply README.md changes
    - name: "Merge develop -> master if changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: develop
        target_branch: master
        github_token: ${{ github.token }}